# Generated by Django 5.2.3 on 2026-06-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload high-quality image (recommended: 800x600px)",
                null=True,
                upload_to="menu_items/",
            ),
        ),
    ]
