# Generated by Django 5.2.3 on 2026-06-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
