# Generated by Django 5.2.3 on 2026-06-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="payment_receipts/"
            ),
        ),
    ]
