# Generated by Django 5.2.3 on 2026-06-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_order_delivery_person_deliveryperson_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
