# Generated by Django 5.2.3 on 2026-06-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_order_customer_latitude_order_customer_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_proof",
            field=models.ImageField(blank=True, null=True, upload_to="delivery_proof/"),
        ),
    ]
